# Generated by Django 4.1.5 on 2023-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aft_sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulksms",
            name="response_recipients",
            field=models.ManyToManyField(to="aft_sms.bulkrecipient"),
        ),
    ]
