# Generated by Django 4.1.5 on 2023-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Koromatangi", "Koromatangi"),
                            ("Lurambi", "Lurambi"),
                            ("Sichirai", "Sichirai"),
                            ("Machakos", "Machakos"),
                            ("Amalemba", "Amalemba"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "user reg",
                "verbose_name_plural": "user regs",
            },
        ),
        migrations.CreateModel(
            name="USSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessionId", models.CharField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=50)),
                (
                    "networkCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("serviceCode", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "ussd",
                "verbose_name_plural": "ussds",
            },
        ),
    ]
