# Generated by Django 4.1.5 on 2023-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aft_ussd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreg",
            name="location",
            field=models.CharField(
                choices=[
                    ("Amalemba", "Amalemba"),
                    ("Machakos", "Machakos"),
                    ("Sichirai", "Sichirai"),
                    ("Koromatangi", "Koromatangi"),
                    ("Lurambi", "Lurambi"),
                ],
                max_length=50,
            ),
        ),
    ]
